Repository instana/nodejs, pull requests merged in 2021-09, with the labels that each got.

#381 fix(tests): added missing pg host to run-tests.sh script
  bin/run-tests.sh
Labels: review and merge

#380 chore(profiling): add missing pre-compiled darwin binary
  packages/autoprofile/addons/.gitignore
  packages/autoprofile/addons/darwin/x64/93/autoprofile.node
Labels: review and merge

#384 fix(docs): added missing node.js development version
  CONTRIBUTING.md
Labels: review and merge

#386 test(refactor): moved env variables to collector package
  .circleci/config.yml
  bin/run-collector-tests.sh
  bin/run-tests.sh
  packages/collector/package.json
  packages/collector/test/.mocharc.json
  packages/collector/test/initEnv.js
Labels: ready for review but do not merge yet

#389 fix(test): make version check more lenient
  packages/shared-metrics/test/dependencies/test.js
Labels: review and merge

#391 feat(tracing): added console.warn & console.error instrumentation
  packages/aws-lambda/test/logging/lambda.js
  packages/aws-lambda/test/logging/test.js
  packages/collector/test/test_util/ProcessControls.js
  packages/collector/test/tracing/logger/bunyan/test.js
  packages/collector/test/tracing/logger/console/app.js
  packages/collector/test/tracing/logger/console/test.js
  packages/collector/test/tracing/logger/pino/test.js
  packages/collector/test/tracing/logger/winston/test.js
  packages/core/src/tracing/index.js
  packages/core/src/tracing/instrumentation/loggers/console.js
  packages/core/test/test_util/common_verifications.js
Labels: WIP

#394 fix(docs): Added hint about being logged in with npm
  CONTRIBUTING.md
Labels: review and merge

#393 test(cleanup): Removed unneeded waitUntilAppIsCompletelyInitialized
  packages/legacy-sensor/test/api/test.js
  packages/legacy-sensor/test/metrics/test.js
Labels: review and merge

#388 Opentelemetry exporter
  .circleci/config.yml
  CONTRIBUTING.md
  bin/run-otel-exporter-tests.sh
  packages/aws-lambda/src/wrapper.js
  packages/core/test/test_util/index.js
  packages/opentelemetry-exporter/.ncurc.json
  packages/opentelemetry-exporter/README.md
  packages/opentelemetry-exporter/bin/prepare-audit.sh
  packages/opentelemetry-exporter/package-lock.json
  packages/opentelemetry-exporter/package.json
  packages/opentelemetry-exporter/src/index.js
  packages/opentelemetry-exporter/test/.eslintrc.js
  packages/opentelemetry-exporter/test/Control.js
  packages/opentelemetry-exporter/test/app.js
  packages/opentelemetry-exporter/test/otel_spans.js
  packages/opentelemetry-exporter/test/test.js
  packages/opentelemetry-exporter/test/tracing.js
  packages/serverless/src/backend_connector.js
  packages/serverless/src/uninstrumentedHttp.js
  packages/shared-metrics/package-lock.json
  test-suite-ports.md
Labels: review and merge
