Repository instana/nodejs, pull requests merged in 2022-08, with the labels that each got.

#579 chore: added docs for running lambda locally with a lambda emulator
  packages/aws-lambda/lambdas/runtime_emulator/.env.template
  packages/aws-lambda/lambdas/runtime_emulator/.gitignore
  packages/aws-lambda/lambdas/runtime_emulator/Dockerfile
  packages/aws-lambda/lambdas/runtime_emulator/README.md
  packages/aws-lambda/lambdas/runtime_emulator/app.js
  packages/aws-lambda/lambdas/runtime_emulator/build-and-run.sh
  packages/aws-lambda/lambdas/runtime_emulator/trigger.sh
  packages/aws-lambda/lambdas/runtime_emulator/utils
  packages/aws-lambda/test/runtime_emulator/README.md
Labels: review and merge

#590 fix(shared-metrics): package.json not being found
  packages/core/src/util/applicationUnderMonitoring.js
  packages/shared-metrics/.eslintignore
  packages/shared-metrics/src/name.js
  packages/shared-metrics/test/cjs-require-in-preload/module/load-instana.js
  packages/shared-metrics/test/cjs-require-in-preload/module/package.json
  packages/shared-metrics/test/cjs-require-in-preload/module/src/app.js
  packages/shared-metrics/test/cjs-require-in-preload/test.js
  packages/shared-metrics/test/ejs-require-in-preload/module/load-instana.cjs
  packages/shared-metrics/test/ejs-require-in-preload/module/package.json
  packages/shared-metrics/test/ejs-require-in-preload/module/src/app.js
  packages/shared-metrics/test/ejs-require-in-preload/test.js
  packages/shared-metrics/test/name_test.js
Labels: review and merge

#593 chore: fixed nvmrc link in contributing.md
  CONTRIBUTING.md
Labels: review and merge

#592 chore: improved bin/clean-aws.js script
  .circleci/config.yml
  bin/clean-aws.js
  package-lock.json
  package.json
  packages/collector/test/tracing/cloud/aws-sdk/v2/s3/test.js
  packages/collector/test/tracing/cloud/aws-sdk/v2/sns/app.js
  packages/collector/test/tracing/cloud/aws-sdk/v2/sns/test.js
  packages/collector/test/tracing/cloud/aws-sdk/v3/s3/test_definition.js
  packages/collector/test/tracing/cloud/aws-sdk/v3/sqs/test_definition.js
Labels: review and merge

#598 chore: updated gitignore files
  .gitignore
  packages/collector/.gitignore
  packages/shared-metrics/.gitignore
Labels: review and merge

#599 chore: updated serverless framework lambdas
  packages/aws-lambda/.eslintignore
  packages/aws-lambda/lambdas/serverless-framework/.gitignore
  packages/aws-lambda/lambdas/serverless-framework/README.md
  packages/aws-lambda/lambdas/serverless-framework/with-layer/index.js
  packages/aws-lambda/lambdas/serverless-framework/with-layer/package-lock.json
  packages/aws-lambda/lambdas/serverless-framework/with-layer/package.json
  packages/aws-lambda/lambdas/serverless-framework/with-layer/serverless.yml
  packages/aws-lambda/lambdas/serverless-framework/with-serverless-offline/index.js
  packages/aws-lambda/lambdas/serverless-framework/with-serverless-offline/package-lock.json
  packages/aws-lambda/lambdas/serverless-framework/with-serverless-offline/package.json
  packages/aws-lambda/lambdas/serverless-framework/with-serverless-offline/serverless.yml
  packages/aws-lambda/lambdas/serverless-framework/with-serverless-webpack/index.js
  packages/aws-lambda/lambdas/serverless-framework/with-serverless-webpack/package-lock.json
  packages/aws-lambda/lambdas/serverless-framework/with-serverless-webpack/package.json
  packages/aws-lambda/lambdas/serverless-framework/with-serverless-webpack/serverless.yml
  packages/aws-lambda/lambdas/serverless-framework/with-serverless-webpack/webpack.config.js
  packages/aws-lambda/lambdas/serverless/.dont-add-instana
  packages/aws-lambda/lambdas/serverless/.eslintrc.js
  packages/aws-lambda/lambdas/serverless/.gitignore
  packages/aws-lambda/lambdas/serverless/README.md
  packages/aws-lambda/lambdas/serverless/index.js
  packages/aws-lambda/lambdas/serverless/package-lock.json
  packages/aws-lambda/lambdas/serverless/serverless.yml
Labels: ready for review but do not merge yet

#602 fix(tracing): fix log4js message format call
  packages/collector/test/tracing/logger/log4js/app.js
  packages/collector/test/tracing/logger/log4js/test.js
  packages/core/src/tracing/instrumentation/loggers/log4js.js
Labels: review and merge, bug
