Repository instana/nodejs, pull requests merged in 2023-06, with the labels that each got.

#802 test: fix bunyan, q, DB2 & OpenTracing tests for Node.js 10 & 12
  packages/collector/test/test_util/isOTelIntegrationEnabled.js
  packages/collector/test/tracing/control_flow/q/test.js
  packages/collector/test/tracing/database/db2/test.js
  packages/collector/test/tracing/logger/bunyan/test.js
  packages/collector/test/tracing/open_tracing/integration_test.js
  packages/core/src/tracing/opentelemetry-instrumentations/wrap.js
Labels: review and merge

#804 chore: fix lock file
  package-lock.json
  packages/collector/package-lock.json
Labels: review and merge

#803 feat(sdk): add method to mark the current span as an error
  packages/collector/test/tracing/api/app.js
  packages/collector/test/tracing/api/app.mjs
  packages/collector/test/tracing/api/test.js
  packages/core/src/tracing/spanHandle.js
  packages/core/test/tracing/spanHandle_test.js
Labels: ready for review but do not merge yet

#779 ci: enable to rerun only the failed tests on CircleCI
  .circleci/config.yml
  CONTRIBUTING.md
  bin/ci_glob_setup.sh
  package.json
  packages/autoprofile/package.json
  packages/aws-fargate/package.json
  packages/aws-lambda-auto-wrap/package.json
  packages/aws-lambda/package.json
  packages/collector/package.json
  packages/core/package.json
  packages/google-cloud-run/package.json
  packages/metrics-util/package.json
  packages/opentelemetry-exporter/package.json
  packages/opentelemetry-sampler/package.json
  packages/serverless/package.json
  packages/shared-metrics/package.json
Labels: review and merge

#805 feat: added node v20 support
  .circleci/config.yml
  native-dep-packs/rebuild-precompiled-addons.sh
  packages/autoprofile/addons/darwin/x64/115/autoprofile.node
  packages/autoprofile/addons/linux/x64/glibc/115/autoprofile.node
  packages/autoprofile/addons/linux/x64/musl/115/autoprofile.node
  packages/autoprofile/precompile/build-all-addons.js
  packages/autoprofile/precompile/docker-opts.js
  packages/collector/test/opentelemetry/app.js
  packages/collector/test/opentelemetry/test.js
  packages/collector/test/tracing/cloud/aws-sdk/v2/dynamodb/test.js
  packages/collector/test/tracing/cloud/aws-sdk/v2/kinesis/test.js
  packages/collector/test/tracing/cloud/aws-sdk/v2/lambda/test.js
  packages/collector/test/tracing/cloud/aws-sdk/v2/s3/test.js
  packages/collector/test/tracing/database/sequelize/test.js
  packages/collector/test/tracing/messaging/node-rdkafka/test.js
  packages/shared-metrics/addons/darwin/x64/115/event-loop-stats.tar.gz
  packages/shared-metrics/addons/darwin/x64/115/gcstats.js.tar.gz
  packages/shared-metrics/addons/linux/x64/glibc/115/event-loop-stats.tar.gz
  packages/shared-metrics/addons/linux/x64/glibc/115/gcstats.js.tar.gz
  packages/shared-metrics/addons/linux/x64/musl/115/event-loop-stats.tar.gz
  packages/shared-metrics/package-lock.json
  packages/shared-metrics/test/esm-loader/test.js
Labels: do not merge, experimental
